environment.yml

update environment.yml to include basic libraries for a dashboard

---

reports/section3.md

Added writing to Section 3

---

reports/section2.md

Add the data description section to the section2.md file. Closes #6.

Add data description component

---

reports/m1_proposal.md

I have combined all the individual proposal sections into 1 document. I also made a couple of minor spelling and grammar corrections and added hyperlinks to our data source. Closes #11

Combine proposal sections

---

LICENSE

I added a creative commons license 
closes #42

fix: add a creative commons license

---

README.md

fix: added contributing and license section to our readme
closes #41

fix: added a contributing and license section

---

src/app.py

This pull request is mostly meant to bring the data in so that team members can work on their own components without having to wait. Very early map graphic with limited functionality.

Add initial map graphic including loading the necessary GeoJSON data

---

reports/m1_proposal.md

Add which feature/variable we would like to implement that is not available in the data. 
closes #43

fix: add to data section of proposal

---

environment.yml

fix: update env

---

src/app.py

added an arrest frequency pie chart on top right corner.
- Changed from a bar chart to pie chart because there are too many arrests 
- changed to top 10 arrests because there are too many on one chart

fix: added arrest freq pie chart

---

src/app.py

Updating the dashboard to add a map toggle that switches between precincts and boroughs. This will make it easier to implement interactivity between different dashboard objects.

Update dashboard to add toggle for map for boroughs vs precincts

---

src/app.py

- added charts
- added helper functions to handle all 3 pie charts together

feat: added gender and age pie charts

---

reports/m2_reflection.md

Drafted initial points for the reflection.
The assignment does not say whether the document needs to be in full sentences or bullet points. In this case I think bullet points is actually more appropriate - the kinds of questions are better suited to list answers with brief rational rather than full sentences that make the information harder to scan/skim/quickly grasp which is what TAs and any potential collaborators will want to be doing with the content anyways.

docs: draft initial points

---

src/app.py

fix: changed "reset all pie charts" buttons location to inside sidebar

---

src/app.py

closes #39
- added calender to side bar
- I can't change the size of the pop up calendar to fit inside the side bar no matter what I do. 
- Need to change size to make it look better

feat: add calendar to side bar

---

src/app.py

fix: fit the calander in sidebar

---

reports/m2_reflection.md

Updated reflection to add missing implementations and some bugs.

docs: Complete reflection

---

src/app.py

There was some extra code present that was fixing geojson serialization issues. This was resolved by changing how we ordered the left and right dataframes in the merge and now the extra code is no longer necessary.

Fix: Refactor code to remove unnecessary geojson transformations

---

src/callbacks/charts.py
src/callbacks/map.py
src/data/data.py
src/utils/__init__.py
src/utils/helpers.py

The calendar object in the sidebar now properly updates both the map and the pie charts based on the date range entered. The map and pie charts are only updated when the "Apply" button is pressed. If the data is filtered down too much to the point that the dataframe is empty, the pie charts will be replaced with grey empty pie charts to indicate there is no data. The map did not play as nicely and currently just returns an empty map if there is an empty dataframe. Could add a future task to implement placeholders for this.

Feat: Add calendar interactivity

---

src/app.py
src/components/general.py

Update the layout of the title to center it. Also moved the filter sidebar button to the top right of the screen.

feat: Update title layout

---

src/utils/helpers.py

- fix: update pie chart so they fit on one screen
- fix: change pie chart titles so that they are centered. 
closes #83

fix: update pie chart

---

src/components/charts.py
src/utils/helpers.py

1. Remove modebars from pie/bar charts
2. Fix placeholder pie/bar charts
3. Hide percentages if pie chart slice is too small
4. Remove numbers to the right of bar chart bars.

Feat: chart visual improvements

---

src/components/general.py

Updated the last updated date to March 9th in the description at the bottom of the dashboard.

feat: update last updated date to March 9th

---

reports/m3_reflection.md

I started working on reflection 3. I've added sections for 
- What has been implemented since milestone 2
- What has not been implemented and why
- What is not working properly
All that's left is:
- What the dashboard does well
- Dashboard limitations
- Potential future improvements and additions

docs: Started on reflection 3

---

src/callbacks/map.py

feat: move legend to left

---

src/components/charts.py
src/components/map.py

Added loading indicators to let the user know the data is loading.

Feat add loading indicators

---

src/callbacks/map.py

Added a dynamic title to the map indicating if it is set to precinct or borough view. Closes #127

feat: Add dynamic map title

---

src/callbacks/charts.py
src/callbacks/map.py

Grey out the map regions if there is no data. Also fixed the chart functionality so that it now updates properly if a region is selected while filters are applied. Closes #125 and #124.

feat: grey out regions

---

src/assets/style.css
src/utils/helpers.py

Remove the bar chart zoom functionality and remove the actions menu from the map chart.

feat: remove chart zoom and actions

---

src/assets/style.css
src/callbacks/map.py

Change cursor functionality:
- Map: Hovering over a region changes the cursor from default to pointer to indicate it can be clicked and selected.
- Bar chart: Hovering over the bar chart no longer shows pointer instead of default cursor.
Closes #148

feat: Change cursor

---

src/components/general.py

Update the last updated date in the about section from March 9th, 2025 to March 14th, 2025.

feat: Update date

---

src/assets/style.css
src/callbacks/buttons.py
src/components/general.py

The sidebar now slides in and out from the left side of the screen instead of just appearing from nowhere. Looks cleaner this way.

feat: add sidebar transitions

---

reports/m4_reflection.md

Milestone 4 reflection
